# Generated by Django 3.2.9 on 2021-11-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0002_auto_20211105_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casts',
            options={'verbose_name': 'Cast'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['type'], 'verbose_name': 'Categorie'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['name'], 'verbose_name': 'Movie'},
        ),
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.FileField(null=True, upload_to='videos%y%m%d'),
        ),
    ]
