# Generated by Django 3.2.9 on 2021-11-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0003_auto_20211107_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(to='Movie.Casts'),
        ),
    ]
