# Generated by Django 3.2.9 on 2021-11-07 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0004_movie_actors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Casts',
            new_name='Cast',
        ),
    ]
